name: 'Gemini Auto Tweet'
description: 'Generate structured release tweets with Gemini AI, including option for image generation.'
author: 'Koki-718'
branding:
  icon: 'twitter'
  color: 'blue'
inputs:
  gemini_api_key:
    description: 'Google Gemini API Key'
    required: true
  enable_image_generation:
    description: 'Enable AI image generation (Imagen)'
    required: false
    default: 'false'

runs:
  using: 'node20'
  main: 'dist/index.js'
